### PR TITLE
Exit with 1 if error is present

### PR DESCRIPTION
**Pull request by robframpton**
Note: this depends on https://github.com/metal/metal-tools-soy/pull/8

### CODE REVIEW

**Comment by eduardolundgren** [comment]
Should we exit process here? I guess @mairatma wasn't performing `exit(1)` on soy errors to prevent stopping a watch for example.

**Comment by jbalsas** [comment]
Hey @eduardolundgren, that should make sense for the `watch` case, but not for single run invocations which should signal its end properly. Not doing it makes it hard to automate or connect with other tooling.

I'm guessing we could detect we're running the `watch` command so we don't exit in that case, @Robert-Frampton?

**Comment by robframpton** [comment]
Yep, should be easy to implement.  I can update this branch.

**Comment by robframpton** [comment]
Hey guys, since we're not passing a custom `handleError` function to the watch task, it will actually remain unaffected by these changes. 

I also realized that I was only setting that property for the `soy` command, but it needed to be set for the `build` command as well, so I made that change and added a test.

**Review by brunobasto — APPROVED** [review]
LGTM

**Comment by jbalsas** [comment]
Awesome, thanks @Robert-Frampton!

**Review by jbalsas — APPROVED** [review]

**Comment by jbalsas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
